export const MY_LEAVE_NAVIGATION = "MY_LEAVE_NAVIGATION";
export const MY_PROFILE_NAVIGATION = "MY_PROFILE_NAVIGATION";
export const MANAGE_LEAVE_NAVIGATION = "MANAGE_LEAVE_NAVIGATION";
export const MANAGE_EMPLOYEE_NAVIGATION = "MANAGE_EMPLOYEE_NAVIGATION";
export const CONFIGURATION_NAVIGATION = "CONFIGURATION_NAVIGATION";

